name: With disabled functions

on: workflow_dispatch

jobs:
  disabled:
    name: Disabled functions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019]
        php: [8.1]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Setup PHP ("exec" and "passthru" disabled)
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        # PS: I would have liked to test disabling ini_get, but then composer fails
        # composer alse needs proc_open, so I cannot test without that either
        ini-values: disable_functions="exec,passthru"

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite with "exec" and "passthru" disabled
      run: composer run-script test-no-cov

    - name: Re-setup PHP (only "exec" disabled)
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        ini-values: disable_functions="exec"

    - name: Run test suite with "exec" disabled
      run: composer run-script test-no-cov

    - name: Re-setup PHP (only "passthru" disabled)
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        ini-values: disable_functions="passthru"

    - name: Run test suite with "passthru" disabled
      run: composer run-script test-no-cov