name: PHP 8.4

on:
  workflow_dispatch:
  schedule: # Run monthly
    - cron: "14 3 20 * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019, macos-13, macos-12]
        php: [8.4]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        extensions: mbstring

    - name: Validate composer.json
      run: composer validate --strict

    - name: Composer install
      run: composer install --prefer-dist --no-progress

    - name: Run phpunit (test cases)
      run: composer run-script test-no-cov

    # Skip phpstan as phpstan does not support php 8.4 yet 
    #- name: Run phpstan
    #  run: composer run-script phpstan

    - name: run phpcs (to check coding style)
      run: composer run-script phpcs-all

    - name: Re-setup PHP, now with "exec" and "passthru" disabled
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        # PS: I would have liked to test disabling ini_get, but then composer fails
        # composer alse needs proc_open, so I cannot test without that either
        ini-values: disable_functions="exec,passthru"

    - name: Run test suite with "exec" and "passthru" disabled
      run: composer run-script test-no-cov

    - name: Re-setup PHP (only "exec" disabled)
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        ini-values: disable_functions="exec"

    - name: Run test suite with "exec" disabled
      run: composer run-script test-no-cov

    - name: Re-setup PHP (only "passthru" disabled)
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        ini-values: disable_functions="passthru"

    - name: Run test suite with "passthru" disabled
      run: composer run-script test-no-cov